chat/urls.py
from django.urls import path
from . import views

app_name = "chat"

urlpatterns = [
    path('', views.home, name='home'),
    path('<str:room>/', views.room, name='room'),
    path('checkview', views.checkview, name='checkview'),
    path('send', views.send, name='send'),
    path('getMessages/<str:room>/', views.getMessages, name='getMessages'),
]

main/urls.py
from django.urls import path
from . import views
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView
from main.views import ProductList, productdetail

app_name = "main"


urlpatterns = [
	path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('img/favicon.ico'))),
    path("", views.homepage, name="homepage"),
    path("products", views.products, name = "products"),
    path("register", views.register, name="register"),
    path("login", views.login_request, name ="login"),
    path("logout", views.logout_request, name= "logout"),
    path("blog/<tag_page>", views.blog, name ="blog"),
    path("user", views.userpage, name = "userpage"),
    path("<article_page>", views.article, name = "article"),
    path('products/', ProductList.as_view()),
    path('products/<int:pk>/', productdetail, name='productdetail'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf import settings 
from django.conf.urls.static import static 
from django.conf.urls import include, url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include ('main.urls')), 
    path('tinymce/', include('tinymce.urls')),
    path("oauth/", include("social_django.urls")),
    path('chat/', include('chat.urls')),
]

if settings.DEBUG: 
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from tinymce.models import HTMLField
from django.contrib.auth.models import User
from django.dispatch import receiver 
from django.db.models.signals import post_save 
from django.db.models import Sum
from datetime import datetime

# Create your models here.
class Product(models.Model):
	product_name = models.CharField(max_length=150)
	product_type = models.CharField(max_length=25)
	product_description = models.TextField()
	affiliate_url = models.SlugField(blank=True, null=True)
	product_image = models.ImageField(upload_to='images/')
	comfort_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	performance_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	durability_average = models.DecimalField(default=0, max_digits=3, decimal_places=1)
	def __str__(self):
		return self.product_name

class Tag(models.Model):
	tag_name = models.CharField(max_length=15, null = True, blank=True)
	tag_slug = models.SlugField()
    
	def __str__(self):
		return self.tag_name


class Article(models.Model):
	article_title = models.CharField(max_length=200)
	article_published = models.DateTimeField(default=datetime.now)
	article_image = models.ImageField(upload_to='images/')
	article_tags = models.ManyToManyField(Tag)
	article_content = models.TextField()
	article_slug = models.SlugField()

	def __str__(self):
		return self.article_title

class Profile(models.Model):   
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	products = models.ManyToManyField(Product)

	@receiver(post_save, sender=User) 
	def create_user_profile(sender, instance, created, **kwargs):
		if created:
			Profile.objects.create(user=instance)

	@receiver(post_save, sender=User) 
	def save_user_profile(sender, instance, **kwargs):
		instance.profile.save()


class Vote(models.Model):   
	profile = models.ForeignKey(Profile, on_delete=models.CASCADE)
	product = models.ForeignKey(Product, on_delete=models.CASCADE)
	comfort = models.IntegerField(default=0)
	performance = models.IntegerField(default=0)
	durability = models.IntegerField(default=0)

	def calculate_averages(self):
			product = self.product
			vote_qs = Vote.objects.filter(product=product)
			vote_count = vote_qs.count()
			comfort_total = vote_qs.aggregate(Sum('comfort'))
			performance_total = vote_qs.aggregate(Sum('performance'))
			durability_total = vote_qs.aggregate(Sum('durability'))
			product.comfort_average = comfort_total['comfort__sum']/vote_count
			product.performance_average = performance_total['performance__sum']/vote_count
			product.durability_average = durability_total['durability__sum']/vote_count
			product.save()


class Room(models.Model):
    name = models.CharField(max_length=1000)
class Message(models.Model):
    value = models.CharField(max_length=1000000)
    date = models.DateTimeField(default=datetime.now, blank=True)
    user = models.CharField(max_length=1000000)
    room = models.CharField(max_length=1000000)

main/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile, Vote
from django.forms.widgets import NumberInput



# Create your forms here.

class NewUserForm(UserCreationForm):
	email = forms.EmailField(required=True)

	class Meta:
		model = User
		fields = ("username", "email", "password1", "password2")

	def save(self, commit=True):
		user = super(NewUserForm, self).save(commit=False)
		user.email = self.cleaned_data['email']
		if commit:
			user.save()
		return user

class UserForm(forms.ModelForm):
	class Meta:
		model = User
		fields = ('username', 'first_name', 'last_name', 'email')

class ProfileForm(forms.ModelForm):
	class Meta: 
		model = Profile
		fields = ('products',)

class VoteForm(forms.ModelForm):
	comfort = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class':'comfort'}))
	performance = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class':'performance'}))
	durability = forms.IntegerField(widget=NumberInput(attrs={'placeholder': ('5'),'type':'range', 'min': '1', 'max': '10', 'class':'durability'}))

	class Meta: 
		model = Vote
		fields = ('comfort', 'performance', 'durability')

main/views.py
from django.shortcuts import  render, redirect
from .models import Product, Article, Tag, Profile
from django.core.paginator import Paginator
from .forms import NewUserForm, UserForm, ProfileForm, VoteForm
from django.contrib.auth import login, authenticate, logout
from django.contrib import messages
from django.contrib.auth.forms import AuthenticationForm
from django.views.generic import ListView 

# Create your views here.
def homepage(request):
	if request.method == "POST":
		product_id = request.POST.get('product_pk')
		product = Product.objects.get(id = product_id)
		request.user.profile.products.add(product)
		messages.success(request,(f'{product} added to wishlist.'))
		return redirect ('main:homepage')	
	product = Product.objects.all()[:4]
	new_posts = Article.objects.all().order_by('-article_published')[:4]
	featured = Article.objects.filter(article_tags__tag_name='Featured')[:3]
	most_recent = new_posts.first()
	return render(request=request, template_name="main/home.html", context={'product':product, 'most_recent':most_recent, "new_posts":new_posts, "featured":featured})

def products(request):
	if request.method == "POST":
		if "score_submit" in request.POST:
			vote_form = VoteForm(request.POST)
			if vote_form.is_valid():
				form = vote_form.save(commit=False)
				form.profile = request.user.profile
				product_id = request.POST.get("product")
				form.product = Product.objects.get(id=product_id)
				form.save()
				form.calculate_averages() 
				messages.success(request,(f'{form.product} product score submitted.'))
				return redirect ("main:products")
			messages.error(request,('Form is invalid.'))
			return redirect ("main:products")
		product_id = request.POST.get("product_pk")
		product = Product.objects.get(id = product_id)
		request.user.profile.products.add(product)
		messages.success(request,(f'{product} added to wishlist.'))
		return redirect ('main:products')
	product = Product.objects.all()
	paginator = Paginator(product, 18)
	page_number = request.GET.get('page')
	page_obj = paginator.get_page(page_number)
	vote_form = VoteForm()
	return render(request = request, template_name="main/products.html", context = {"product":product, "page_obj":page_obj, "vote_form":vote_form})
#Products
class ProductList(ListView):
    model = Product
	

def productdetail(request,id):
    product = Product.objects.get(id = id)
    return render(request, 'main/product.html', {'product': product})

def register(request):
	if request.method == "POST":
		form = NewUserForm(request.POST)
		if form.is_valid():
			user = form.save()
			login(request, user)
			messages.success(request, "Registration successful." )
			return redirect("main:homepage")
		messages.error(request, "Unsuccessful registration. Invalid information.")
	form = NewUserForm
	return render (request=request, template_name="main/register.html", context={"form":form})

def login_request(request):
	if request.method == "POST":
		form = AuthenticationForm(request, data=request.POST)
		if form.is_valid():
			username = form.cleaned_data.get('username')
			password = form.cleaned_data.get('password')
			user = authenticate(username=username, password=password)
			if user is not None:
				login(request, user)
				messages.info(request, f"You are now logged in as {username}.")
				return redirect("main:homepage")
			else:
				messages.error(request,"Invalid username or password.")
		else:
			messages.error(request,"Invalid username or password.")
	form = AuthenticationForm()
	return render(request=request, template_name="main/login.html", context={"form":form})


def logout_request(request):
	logout(request)
	messages.info(request, "You have successfully logged out.") 
	return redirect("main:homepage")

def blog(request, tag_page):
	if tag_page == 'articles':
		tag =''
		blog = Article.objects.all().order_by('-article_published')
	else:
		tag = Tag.objects.get(tag_slug=tag_page)
		blog = Article.objects.filter(article_tags=tag).order_by('-article_published')
	paginator = Paginator(blog, 25)
	page_number = request.GET.get('page')
	blog_obj = paginator.get_page(page_number)
	return render(request=request, template_name="main/blog.html", context={"blog":blog_obj, "tag":tag})

def article(request, article_page):
    article = Article.objects.get(article_slug=article_page)
    return render(request=request, template_name='main/article.html', context={"article": article})

def userpage(request):
	if request.method == "POST":
		user_form = UserForm(request.POST, instance=request.user)
		profile_form = ProfileForm(request.POST, instance=request.user.profile)
		if user_form.is_valid():
		    user_form.save()
		    messages.success(request,('Your profile was successfully updated!'))
		elif profile_form.is_valid():
		    profile_form.save()
		    messages.success(request,('Your wishlist was successfully updated!'))
		else:
		    messages.error(request,('Please correct the error below.'))
		return redirect ("main:userpage")
	user_form = UserForm(instance=request.user)
	profile_form = ProfileForm(instance=request.user.profile)
	return render(request = request, template_name ="main/user.html", context = {"user":request.user, 
		"user_form": user_form, "profile_form": profile_form })

main/templates/main/article.html
{% extends "main/header.html" %}

{% block content %}

<div class="article-banner text-center">
    <br><br>
    <div class="container">
        <h1 class=" article-heading font-weight-bold">{{ article.article_title }}</h1>
        <p class="font-weight-bold" style="font-size:15px">{{ article.article_published }}</p>
        {% for tag in article.article_tags.all %}
        <span class="badge badge-dark" style="font-size:14px; color:white">{{ tag }}</span>
        {% endfor %}
        
    </div>
</div>
<div class="container">
    <br>
    <p>{{ article.article_content|safe }}</p>
</div>

<style>
    .article-banner { 
        background-image:
        /* The image fade to white */
        linear-gradient(to left, rgba(0,0,0,0) 10%, #fff 85%),
        /* The image used */
        url("{{ article.article_image.url }}");
        /* Set a specific height */
        height:200px;
        /* Create the parallax scrolling effect */
        background-attachment: fixed;
        background-position: center bottom;
        background-repeat: no-repeat;
        background-size: cover;
        z-index: auto;
        position: relative;
    }

    /* all devices up to 786px */
    @media only screen and (max-width:768px) {
       .article-heading {font-size:22px !important;}
   }

   /* devices 768px to 1200px */
   @media only screen and (min-width:768px) and (max-width:1200px) {
      .article-heading {font-size:27px !important;}
  }
</style>

{% endblock %}

main/templates/main/blog.html
{% extends "main/header.html" %}

{% block content %}

<!--Blog-->
<div class="container py-5">
    {% if tag %}
    <h1 class="font-weight-bold">{{ tag }}</h1>
    {% else %}
    <h1 class="font-weight-bold">Articles</h1>
    {% endif %}
    <hr>
    <br>
    <div class="row">
        {% for b in blog %}
        <a href="/{{ b.article_slug }}" style="text-decoration: none">
            <div class="col-12 pb-4 text-dark">
                <div class="row">
                    <div class="col-lg-4 col-md-6 col-sm-12 my-auto">
                       <img src="{{ b.article_image.url }}" class="img-fluid rounded" alt="{{ b.article_name }}">
                   </div>
                   <div class="col-lg-8 col-md-6 col-sm-12 my-auto">
                       <p>
                        {% for tag in b.article_tags.all %}
                        <span class="badge badge-primary" style ="font-size:14px; color: white">{{ tag }}</span>
                        {% endfor %}
                    </p>
                    <h5>{{ b.article_title }}</h5>
                    <p class="card-text text-muted" style="font-size:12px">{{ b.article_published }}</p>
                    <p>{{ b.article_content|safe|truncatewords:25 }}</p>
                    <button class="btn btn-outline-primary btn-sm">View post</button>
                </div>   
            </div>
        </div>
    </a>
    {% endfor %}
</div>
<!--Pagination-->
<div class="container"> 
    <div class="pagination justify-content-center">
        <span class="step-links">
            {% if blog.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ blog.previous_page_number }}">previous</a>
            {% endif %}
            <span class="current">
                Page {{ blog.number }} of {{ blog.paginator.num_pages }}
            </span>
            {% if blog.has_next %}
            <a href="?page={{ blog.next_page_number }}">next</a>
            <a href="?page={{ blog.paginator.num_pages }}">last &raquo;</a>
            {% endif %}
        </span>
    </div>
</div>
<!--end of Pagination-->
</div>

{% endblock %}

main/templates/main/checkout.html
{% extends "main/header.html" %}

    {% block content %}

    <div>
      <br><br>
      <h2> Checkout </h2>
      <br><br>
      <table style="width:100%">
        <tr style=" font-size: 20px">
          <th>Name</th>
          <th>Price</th>
        </tr>
          
        {% for c in cart.all %}
        <tr>
          <td>{{ c.product_name }}</td>
          <td>${{ c.product_price }}</td>
        </tr>
        {% endfor %}

        <tr>
          <td style="padding-top:30px">Total</td>
          <td>${{ total }}</td>
        </tr>
      </table>
    </div>

    {% endblock %}

main/templates/main/header.html
<!DOCTYPE html>
<html>
<head>
  <!-- Required meta tags -->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>WritersEmpire</title>
  {% load static %}
  <link rel="icon" type="image/png" sizes="32x32" href="{% static 'img/favicon-black.png' %}">
  
  <!--Main CSS-->
  <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
  <!--Bootstrap CSS-->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <!--Fonts-->
  <script src="https://kit.fontawesome.com/4341ccac6b.js" crossorigin="anonymous"></script>
  <link href="https://fonts.googleapis.com/css2?family=Ubuntu:wght@300&display=swap" rel="stylesheet">
</head>
<body>
  
  {% include 'main/includes/navbar.html' %}

  {% include 'main/includes/messages.html' %}

  {% block content %}

  {% endblock %} 

  {% include "main/includes/footer.html" %}
  <!--Main JS-->
  <script src="{%static 'js/app.js' %}"></script>
  <script src="{%static 'js/jquery.js' %}"></script>
  <!-- Optional Javascript -->
  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>
</html>

main/templates/main/login.html
{% extends "main/header.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Login--> 
<div class="container py-5">
	<h1 class="font-weight-bold">Login</h1>
	<hr>
	<br>
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}
		
		<br>
		<button class="btn btn-primary" type="submit">Login</button>
		<p><a href="">Forgot Password?</a></p>	
	</form>
	<br><br>
	
</div>
<style>
form{
	position: relative;
	left: 250px;
	border: 1px solid grey;
	border-radius: 1%;
	text-align: left;
	padding: 15px;
	width: 50%;

}
</style>

{% endblock %}	

main/templates/main/products.html
{% extends "main/header.html" %}

{% block content %}

{% load crispy_forms_tags %}

<!--Products-->
<div class="container py-5">
    <h1 class="font-weight-bold">Products</h1>
    <hr>
    <ul>
        {% for product in object_list %}
            <li><a href="{% url 'productdetail' product.id %}">{{ product.product_title }} </a></li>
        {% endfor %}
    </ul>
    <br>
    <div class="row">
        {% for p in page_obj %}         
        <div class="col-sm-12 col-md-6 col-lg-4 pb-4">
            <div class="card h-100" style="border:none">
                <img src="{{ p.product_image.url }}" class="card-img-top" alt="{{ p.product_name }}" style="width: auto; height: 200px; object-fit: scale-down;">
                <div class="card-body">
                    <h5 class="card-title">{{ p.product_name }}</h5>
                    <p class="card-text text-muted" style="font-size:12px">{{ p.product_type }}</p>
                    <p class="card-text">{{ p.product_description }}</p>
                    <p class="text-muted" style="font-size:12px">Comfort: {{ p.comfort_average }} | Performance: {{ p.performance_average }} | Durability: {{ p.durability_average }}</p>
                    <div class="row">
                        <div class="col-3 text-center">
                            {% if user.is_authenticated %}
                            <form method="post">
                                {% csrf_token %}
                                <input type="hidden" value="{{p.pk}}" name="product_pk">
                                <button type="submit" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</button>
                            </form>
                            {% else %}
                            <a href="/register" class="btn btn-outline-primary" style="font-size:18px; border-radius: 50%">★</a>
                            {% endif %}
                        </div>
                        <div class="col-4 text-center">
                            <a class="btn btn-outline-primary" data-toggle="collapse" href="#collapse{{p.pk}}" role="button" aria-expanded="false" aria-controls="collapse{{p.pk}}">Review</a> 
                        </div>
                        <div class="col-5 text-center">
                            <a href="{{ p.affiliate_url }}" class="btn btn-warning">Buy now</a>                              
                        </div>
                    </div> 
                </div> 
                <div class="collapse" id="collapse{{p.pk}}">
                    <div class="card card-body shadow">
                        <h6>Product Score: {{ p.product_name }}</h6>
                        <hr>
                        <form method="post">
                            {% csrf_token %}
                            {% for field in vote_form %}
                            <div class="row">
                                <div class="col-10" id="slider_{{field.name}}_{{p.pk}}" onclick="sliderUpdate('{{field.name}}', {{p.pk}})">{{field|as_crispy_field}}</div>
                                <div class="col-2 my-auto">
                                    <h6 class="text-center"><span id="score_{{field.name}}_{{p.pk}}" class=text-dark>5</span></h6>
                                </div>
                            </div>
                            {% endfor %}
                            <div class="text-right">
                                {% if user.is_authenticated %}
                                <input type="hidden" value="{{p.pk}}" name="product">
                                <button type="submit" name="score_submit" class="btn btn-outline-primary">Submit Score</button>
                                {% else %}
                                <a href="/register" class="btn btn-outline-primary">Register</a>
                                {% endif %}
                            </div>
                        </form>
                    </div>
                </div>
            </div> 
        </div>
        {% endfor %}
    </div>



    <!--Pagination-->
    <div class="container">
        <div class="pagination justify-content-center">
            <span class="step-links">
                {% if page_obj.has_previous %}
                <a href="?page=1">&laquo; first</a>
                <a href="?page={{ page_obj.previous_page_number }}">previous</a>
                {% endif %}

                <span class="current">
                    Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
                </span>

                {% if page_obj.has_next %}
                <a href="?page={{ page_obj.next_page_number }}">next</a>
                <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
                {% endif %}
            </span>
        </div>
    </div>
    <!--end of Pagination-->
    
</div>


<script>
    function sliderUpdate(field, pk) {
        document.getElementById("score_" + field + "_" + pk).innerText = document.getElementById("slider_" + field + "_" + pk).getElementsByClassName(field)[0].value ;
    }
</script> 

<style>

    #id_comfort, #id_performance, #id_durability {
        -webkit-appearance: none;
        width: 100%;
        border-radius: 0px;  
        height: 25px;
        background: #ffff;
        outline: none;
        opacity: 1;
        -webkit-transition: .2s;
        transition: opacity .2s;
    }

    #id_comfort::-webkit-slider-runnable-track, #id_performance::-webkit-slider-runnable-track, #id_durability::-webkit-slider-runnable-track {
      -webkit-appearance: none;
      width: 100%;
      height: 15px;
      border-radius: 0px;  
      background: #fff;
      outline: none;
      opacity: 1;
      -webkit-transition: .2s;
      transition: opacity .2s;
  }


  #id_comfort::-webkit-slider-thumb, #id_performance::-webkit-slider-thumb, #id_durability::-webkit-slider-thumb {
    -webkit-appearance: none;
    border-radius: 0px;  
    appearance: none;
    width: 25px;
    height: 25px;
    background: #007bff;
    cursor: pointer;
}


#id_comfort::-moz-range-thumb, #id_performance::-moz-range-thumb, #id_durability::-moz-range-thumb {
    -webkit-appearance: none;
    border-radius:0px;
    width: 25px;
    height: 25px;
    background: #007bff;
    cursor: pointer;
}

#id_comfort::-moz-range-track, #id_performance::-moz-range-track, #id_durability::-moz-range-track {
    -webkit-appearance: none;
    border-radius:0px;
    width: 25px;
    height: 25px;
    background: #007bff;
    cursor: pointer;
}






</style>
{% endblock %}

main/templates/main/register.html
{% extends "main/header.html" %}

{% block content %} 

{% load crispy_forms_tags %}         

<!--Register--> 
<div class="container py-5">
	<h1 class="font-weight-bold">Register</h1>
	<hr>
	<br>
	<form method="POST">
		{% csrf_token %}
		{{ form|crispy }}                    
		<br>
		<button class="btn btn-primary" type="submit">Register</button>
	</form>
	<br><br>
	<p>If you already have an account, <a href="/login">login</a> instead.</p>
</div>


<style>
form{
	position: relative;
	left:250px;
	border: 1px solid grey;
	border-radius: 1%;
	text-align: left;
	padding: 15px;
	width: 50%;
	box-shadow: 1px 1px 0px 0px grey;
}


</style>

{% endblock %}